name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  debug:
    name: Debug Event
    runs-on: ubuntu-latest
    steps:
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1

  do_local:
    name: Do Local
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' ||
      github.pull_request.head.repo.fork == false
    steps:
      - name: Check flags
        run: echo "pull request not from fork"
  do_fork:
    name: Do Fork
    runs-on: ubuntu-latest
    if: |
      github.pull_request.head.repo.fork == true
    steps:
      - name: Check flags
        run: echo "pull request from fork"
    
